[package]
name = "sentry"
version = "0.1.0"
authors = ["hello <hello@ifnot.cc>"]

[dependencies]
sentry = { git = "https://github.com/lfany/sentry-rust.git" }
toml = "0.4"
serde = "1.0.11"
serde_derive = "1.0.11"
url = "1.5.1"